- name: Ensure app directory exists
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0755"

- name: Create virtualenv as root
  command: python3 -m venv {{ app_dir }}/venv
  args:
    creates: "{{ app_dir }}/venv/bin/activate"

- name: Fix venv permissions
  file:
    path: "{{ app_dir }}/venv"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    recurse: true

- name: Ensure pip in venv
  command: "{{ app_dir }}/venv/bin/python -m ensurepip --upgrade"
  args:
    creates: "{{ app_dir }}/venv/bin/pip"

- name: Upload Flask app directory
  copy:
    src: web_server_with_login/
    dest: "{{ app_dir }}/"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0755"

- name: Upload requirements.txt
  copy:
    src: requirements.txt
    dest: "{{ app_dir }}/requirements.txt"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0644"

- name: Install Python dependencies in venv
  pip:
    requirements: "{{ app_dir }}/requirements.txt"
    executable: "{{ app_dir }}/venv/bin/pip"

